name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create config.js with environment variables
      run: |
        cat > config.js << 'EOF'
        // Configuration de l'application Google Sheets AI Matcher
        // Variables d'environnement pour le déploiement
        
        const APP_CONFIG = {
            // Configuration Google OAuth
            GOOGLE: {
                // Client ID Google
                CLIENT_ID: '${{ secrets.GOOGLE_CLIENT_ID }}',
                
                // Clé API Google (requise pour l'accès aux APIs)
                API_KEY: '${{ secrets.GOOGLE_API_KEY }}',
                
                // Scopes nécessaires pour accéder aux Google Sheets
                SCOPES: 'https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive.readonly',
                
                // APIs Google à charger
                DISCOVERY_DOCS: [
                    'https://sheets.googleapis.com/$discovery/rest?version=v4',
                    'https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'
                ]
            },
            
            // Configuration OpenAI
            OPENAI: {
                // Clé API OpenAI
                API_KEY: '${{ secrets.OPENAI_API_KEY }}',
                
                // Modèle à utiliser
                MODEL: 'gpt-3.5-turbo',
                
                // Paramètres du modèle
                MAX_TOKENS: 10,
                TEMPERATURE: 0,
                
                // URL de l'API
                API_URL: 'https://api.openai.com/v1/chat/completions'
            },
            
            // Configuration du traitement
            PROCESSING: {
                // Nombre de profils à traiter par lot
                // Réduisez si vous avez des timeouts, augmentez pour plus de vitesse
                BATCH_SIZE: 50,
                
                // Délai entre les lots (en millisecondes)
                BATCH_DELAY: 1000,
                
                // Nombre maximum de tentatives en cas d'erreur
                MAX_RETRIES: 3,
                
                // Délai entre les tentatives (en millisecondes)
                RETRY_DELAY: 2000
            },
            
            // Configuration de l'interface utilisateur
            UI: {
                // Animations
                ENABLE_ANIMATIONS: true,
                
                // Notifications
                SHOW_NOTIFICATIONS: true,
                
                // Thème
                THEME: 'light'
            },
            
            // Configuration de l'export
            EXPORT: {
                // Couleurs pour les résultats
                COLORS: {
                    MATCH: '#d4edda',
                    NO_MATCH: '#f8d7da',
                    PARTIAL: '#fff3cd'
                }
            },
            
            // Configuration de debug
            DEBUG: {
                // Activer les logs détaillés
                VERBOSE_LOGGING: false,
                
                // Afficher les requêtes API
                LOG_API_REQUESTS: false,
                
                // Mode développement
                DEV_MODE: false
            }
        };
        
        // Export pour Node.js (si utilisé)
        if (typeof module !== 'undefined' && module.exports) {
            module.exports = APP_CONFIG;
        }
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,README.md,.gitignore'